### ISSUE TITLE
Switch to GitHub Actions

### ISSUE THREAD

**Issue by Hongbo-Miao** [snap-stanford/deepsnap#13]
I am taking CS224W, just saw this project : )

Just a suggestion switching from Travis to GitHub Actions when this project is still young (later will take more effects), because 

- Due to recent update, Travis added many limitations and also it is slow.
- GitHub is free, faster, and support "apps" through [Marketplace](https://github.com/marketplace) making it much more powerful.

Here is speed comparison for one of my repo between Travis and GitHub Actions:

**1. Travis**
![image](https://user-images.githubusercontent.com/3375461/104369243-1acc1f00-5558-11eb-9099-0893515e1959.png)

**2. GitHub Actions**
![image](https://user-images.githubusercontent.com/3375461/104369867-0ccace00-5559-11eb-952e-7c38627ee981.png)

**Comment by zechengz** [comment]
Switched
