### ISSUE TITLE
Outdated PyPI version causing container_abcs ImportError

### ISSUE THREAD

**Issue by nbingo** [snap-stanford/deepsnap#32]
When importing `Graph` from `deepsnap.graph`, I get the following error:

```
ImportError                               Traceback (most recent call last)
/tmp/ipykernel_119/3679505279.py in <module>
      1 import torch.optim as optim
      2 from torch_geometric.data import DataLoader
----> 3 from deepsnap.graph import Graph
      4 from deepsnap.batch import Batch
      5 from deepsnap.dataset import GraphDataset

/opt/conda/lib/python3.9/site-packages/deepsnap/__init__.py in <module>
      7 import deepsnap.batch
      8 import deepsnap.hetero_graph
----> 9 import deepsnap.hetero_gnn
     10 
     11 import networkx as _netlib

/opt/conda/lib/python3.9/site-packages/deepsnap/hetero_gnn.py in <module>
      5 
      6 from torch import Tensor
----> 7 from torch._six import container_abcs
      8 from torch_geometric.nn.inits import reset
      9 from torch_sparse import matmul

ImportError: cannot import name 'container_abcs' from 'torch._six' (/opt/conda/lib/python3.9/site-packages/torch/_six.py)
```

After some looking, I saw that this was fixed in [this commit](https://github.com/snap-stanford/deepsnap/blob/c4c90d61bcaded186ce532d0c198976fe6f24501/deepsnap/hetero_gnn.py#L1) on June 19th, but the latest update to PyPI was on April 7, so it still persists when pulling using pip. Could a new version be pushed to PyPI?

Thanks!

**Comment by zechengz** [comment]
Hi, thanks for pointing out this. I will update it tomorrow and will let you know once it is updated on PyPI.

**Comment by zechengz** [comment]
Hi, I have updated the DeepSNAP to [v0.2.1](https://pypi.org/project/deepsnap/). Please let me know if you have other questions. Thanks.

**Comment by nbingo** [comment]
Great, thank you!
