### ISSUE TITLE
CORA Node Classification example fails on old cpus

### ISSUE THREAD

**Issue by frg100** [snap-stanford/deepsnap#9]
When the [CORA Node Classification example](https://github.com/snap-stanford/deepsnap/blob/master/examples/node_classification_cora.py) is run on old cpus (eg. madmax), the line that loads the dataset `pyg_dataset = Planetoid('./cora', name, transform=T.TargetIndegree())`, throws a `Illegal instruction (core dumped)` error

**Comment by xhe1997** [comment]
Hi frg100, this looks like a pytorch geometric problem instead of a deepsnap problem.
